# Generated by Django 4.2 on 2026-01-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaigncategory_alter_campaign_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='fundtracer_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/'),
        ),
    ]
