# Generated by Django 4.2.16 on 2026-01-20 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_add_campaign_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='documents_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CampaignDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('BANK_STATEMENT', 'Bank Statement'), ('NGO_REGISTRATION', 'NGO Registration Certificate'), ('TAX_CERTIFICATE', 'Tax Certificate'), ('OTHER', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='campaign_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
