# Generated by Django 4.2 on 2026-01-20 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaign_documents_verified_campaigndocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampaignDocument',
        ),
    ]
