# Generated by Django 4.2.16 on 2026-01-21 11:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_delete_campaigndocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('due_date', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='milestones/')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('campaign', 'order')},
            },
        ),
    ]
